/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import static java.util.Collections.rotate;

public class App {

    public static void main(String[] args) {
        bitmap image = new bitmap();
        image.ReadMyImg(args[0]);
        if (args[3]=="rotate") {
            try {

                // Reading original image
                BufferedImage originalImg = ImageIO.read(
                        new File("D:/test/Image.jpeg"));

                // Getting and Printing dimensions of original
                // image
                System.out.println("Original Image Dimension: "
                        + originalImg.getWidth() + "x"
                        + originalImg.getHeight());

                // Creating a subimage of given dimensions
                BufferedImage SubImg = image.rotate(originalImg);

                // Printing Dimensions of new image created
                // (Rotated image)
                System.out.println("Cropped Image Dimension: "
                        + SubImg.getWidth() + "x"
                        + SubImg.getHeight());

                // Creating new file for rotated image
                File outputfile = new File("D:/test/ImageRotated.jpeg");

                // Writing image in new file created
                ImageIO.write(SubImg, "jpg", outputfile);

                // Printing executed message
                System.out.println("Your Image is rotate " + outputfile.getPath());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        if (args[2]=="Pixilate"){
            image.Pixilate();
        }
        if (args[4]=="Invert"){
            image.Invert();
        }
        if (args[5]=="BlackandWhite"){
            image.BlackandWhite();
        }
    image.writeImage(String.valueOf(new File(args[1])));
    }
}
