/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;
import java.io.File;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        Bitmap image = new Bitmap();
        File file = new File (args[0]);
        System.out.println(Arrays.toString(args));

        image.readMyImg(file);

        if(args[2].equals("pixilate"))
            image.writeImage(new File(args[1]),image.pixilate());

        else  if(args[2].equals("Invert"))
        {
            image.writeImage(new File(args[1]),image.invert());
        }
         else  if(args[2].equals("rotate"))
            image.writeImage(new File(args[1]),image.rotate());

    }

}
